---
title: "NUTS using Rcpp"
date: "2021-10-28"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: false
    number_sections: true  ## if you want number sections at each table header
---

```{r library}
library(dplyr)
library(ggplot2)
library(gridExtra)
```

# Truncated Normal

$$ (\theta_1, \theta_2) \sim N(0, I) I(\theta_1 > 0) I(\theta_2 > 0)$$

* 변환 $\eta_1 = \log \theta_1,~\eta_2 = \log \theta_2$를 이용 

```{r}
Rcpp::sourceCpp("src/NUTS.cpp")
```

* parameter
```{r}
theta0 <- c(0, 0)
n_iter <- as.integer(1e5)
M_adapt <- as.integer(1e4)
M_diag0 <- c(1, 1)
max_treedepth <- 10
```

* sampling
```{r, cache=TRUE}
set.seed(123)
theta <- NUTS(theta0, n_iter, M_diag0, M_adapt, max_treedepth)
```

* traceplot
```{r}
theta <- theta %>% t() %>% as.data.frame()
colnames(theta) <- c("theta1", "theta2")
theta$idx <- 1:n_iter
# theta <- theta %>% filter(idx > M_adapt)

g1 <- ggplot(data = theta) +
    geom_line(aes(x = idx, y = theta1))
g2 <- ggplot(data = theta) +
    geom_line(aes(x = idx, y = theta2))
print(grid.arrange(g1, g2))
```

* transform and visualize
```{r}
theta %>%
    mutate(theta1 = exp(theta1), theta2 = exp(theta2)) %>%
    ggplot(mapping = aes(x = theta1, y = theta2)) +
    geom_point()
```